
###
GET http://localhost:9000/api/inscription/all/611bb47b42102c26999deec0 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTFiYjQ3YjQyMTAyYzI2OTk5ZGVlYzAiLCJpYXQiOjE2MjkzNzY1Nzd9.Mhzv1EVtZKWkj_R467novnMXAtXEZiVlmMhkLJEX-BU


###
GET http://localhost:9000/api/inscription/approved/611bb47b42102c26999deec0 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTFiYjQ3YjQyMTAyYzI2OTk5ZGVlYzAiLCJpYXQiOjE2MjkzNzY1Nzd9.Mhzv1EVtZKWkj_R467novnMXAtXEZiVlmMhkLJEX-BU

###
GET http://localhost:9000/api/inscription/rejected/611bb47b42102c26999deec0 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTFiYjQ3YjQyMTAyYzI2OTk5ZGVlYzAiLCJpYXQiOjE2MjkzNzY1Nzd9.Mhzv1EVtZKWkj_R467novnMXAtXEZiVlmMhkLJEX-BU

###
GET http://localhost:9000/api/inscription/pending/611bb47b42102c26999deec0 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTFiYjQ3YjQyMTAyYzI2OTk5ZGVlYzAiLCJpYXQiOjE2MjkzNzY1Nzd9.Mhzv1EVtZKWkj_R467novnMXAtXEZiVlmMhkLJEX-BU

###
POST http://localhost:9000/api/inscriptionByDNI HTTP/1.1
Content-Type: application/json

{
  "DNI" : 41502896,
  "email":"manu.omkk@gmail.com"
}


###
GET http://localhost:9000/api/inscription/6124420eccd8a000162694be HTTP/1.1

###
DELETE http://localhost:9000/api/inscription/611bb47b42102c26999deec0 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTFiYjQ3YjQyMTAyYzI2OTk5ZGVlYzAiLCJpYXQiOjE2MjkzNzY1Nzd9.Mhzv1EVtZKWkj_R467novnMXAtXEZiVlmMhkLJEX-BU
###
POST http://localhost:9000/api/localhost:9000/api/inscription HTTP/1.1
Content-Type: application/json

{ 
  "name":"Jorge",
  "lastname":"ABCS",
  "email":"jorge@gmail.com",
  "DNI":"30000000",
  "numberCell":"+543743519395",
  "provinceOrigin":"Misiones",
  "locationOrigin":"Jardín América",
  "dateBirth":"1990-12-11",
    "nameCar": "El tigre",
    "registrationCar":"abs-112",
    "colorCar":"Verde",
    "yearCar": 1999,
    "versionCar":"Personalizado",
    "styleCar":"AMI8",
    "VTV":true,
    "arrivalDate":"2021-12-11",
    "dateToProvince":"2021-11-19",
    "travelPeople":2
}