###
POST http://localhost:9000/api/inscription HTTP/1.1
Content-Type: application/json

{
  "name":"Mauro Cristian Emanuel",
  "lastname":"Omiñuka",
  "email":"ominuka.mauro@gmail.com",
  "DNI":"41503896",
  "numberCell":"+543743519395",
  "provinceOrigin":"Misiones",
  "locationOrigin":"Jardín América"
}

###
###
GET http://localhost:9000/api/inscription/61111ec822958e1dfbaa6253 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTExMWVjODIyOTU4ZTFkZmJhYTYyNTMiLCJpYXQiOjE2Mjg1MzUxNjh9.n6itCrKVXmtsMZyWcjNJ3AWIHRqt2JUEZvu0GG9QKew